# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

@pytest.mark.usefixtures("browser")
class TestCategorysearch():

  
  def test_categorysearch(self):
    self.driver.get("http://shop-xo.hctestedu.com/")
    self.driver.find_element(By.XPATH, "//span[contains(.,\'汽车用品\')]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".am-margin-left-sm > span:nth-child(1)").text == "筛选出"
  
