# Generated by Selenium IDE
import pytest
import allure
from selenium import webdriver
from pages.hcsc_home_page import HCHomePage
from pages.hcsc_person_center_page import PersonCenterPage
from utils.conftest import browser


@pytest.mark.usefixtures("browser")
@allure.feature("登录")
@allure.story('登录')
@allure.severity('critical')
class TestLogin():

    def test_login(self,browser):
        driver=browser
        HCHomePage.to_login(driver)
        HCHomePage.to_person_center(driver)
        # PersonCenterPage.toinfoManager(browser)
