# Generated by Selenium IDE
import pytest
import allure
from pages.home_page import HCHomePage
from pages.person_center_page import PersonCenterPage
from utils.conftest import browser


@pytest.mark.usefixtures("browser")
@allure.feature("登录")
@allure.story('登录')
@allure.severity('critical')
class TestLogin():

    def test_login(self,browser):
        driver = browser
        HCHomePage.to_login(self,driver)
        HCHomePage.to_person_center(self,driver)
        PersonCenterPage.to_info_manager(self,driver) # 进入个人中心


