# -- coding: utf-8 --
# @Time : 6/9/22 4:12 PM
# @Project : HCWebTest
# @Author : Denis Yu
# @File : test_place_order.py
# @Software: PyCharm
# Generated by Selenium IDE
import pytest
import allure
from pages.home_page import HCHomePage
from pages.pdp import ProductDetailPage
from testcases.test_check_out import CheckOutPage
from utils.conftest import browser


@pytest.mark.usefixtures("browser")
@allure.feature("下单流程")
@allure.story('下单')
@allure.severity('critical')

class TestPlaceOrder:

    def test_place_order(self,browser):
        driver = browser
        HCHomePage.to_login(self,driver)
        HCHomePage.search_product_by_keyword(self,driver,"连衣裙")
        ProductDetailPage.addToCart(self,driver)
        CheckOutPage.checkout(self,driver)

